#!/bin/sh

HOSTIP=$1
WORKDIR=$2

cd $WORKDIR

openssl genrsa -out ca-key.pem 2048
openssl req -subj "/C=CN" -new -x509 -days 36500 -key ca-key.pem -out ca.pem
openssl genrsa -out server-key.pem 2048

openssl req -subj "/CN=$HOSTIP" -new -key server-key.pem -out server.csr

echo subjectAltName = IP:$HOSTIP,IP:127.0.0.1 > extfile.cnf
openssl x509 -req -days 36500 -in server.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile extfile.cnf

openssl genrsa -out key.pem 2048
openssl req -subj '/CN=client' -new -key key.pem -out client.csr

echo extendedKeyUsage = clientAuth > extfile.cnf
openssl x509 -req -days 36500 -in client.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out cert.pem -extfile extfile.cnf

chmod -v 0400 ca-key.pem key.pem server-key.pem
chmod -v 0444 ca.pem server-cert.pem cert.pem

